extends Node
class_name BossDatabase
## Per-colour boss identity: which model it wears and what its telegraphed
## special attack does.
##
## Each of the five MTG colours gets one boss. The visual scenes are generated by
## tools/boss_character_builder.gd and are all normalized to 1.7 units tall, so
## `model_scale` here is the single knob controlling how physically large a boss
## is - and, through GameSettings.get_boss_anim_speed(), how slowly it animates.

## Boss visual scenes are looked up by path rather than preload()ed so a missing
## or not-yet-built scene degrades to the melee fallback in EnemyBase instead of
## failing to parse this script and taking the whole project down with it.
const VISUAL_SCENES := {
	"Red": "res://scenes/bosses/fire_giant.tscn",
	"Blue": "res://scenes/bosses/frost_giant.tscn",
	"Green": "res://scenes/bosses/treant.tscn",
	"White": "res://scenes/bosses/white_paladin.tscn",
	"Black": "res://scenes/bosses/zombie_lord.tscn",
}

## Bigger = slower animations (see GameSettings.boss_anim_reference_scale, which
## is set to the smallest of these so no boss ends up animating faster than 1.0x).
const MODEL_SCALES := {
	"Red": 2.4,
	"Blue": 2.6,
	"Green": 2.9,
	"White": 2.1,
	"Black": 2.3,
}

## Telegraphed, dodgeable special attacks.
##
## `impact_fraction` is where in the clip the hit lands, as a fraction of the
## clip's own length. Expressing it that way rather than in seconds means the
## windup automatically stretches for bigger bosses (whose clips play slower),
## so the tell stays readable instead of the damage arriving before the swing.
##
## `shape` is "circle" (centred on the boss) or "cone" (a `angle`-degree arc
## opening along the boss's facing, so it can be dodged by getting behind it).
const SPECIALS := {
	"Red": {
		"display_name": "Whirlwind",
		"shape": "circle",
		"radius": 6.5,
		"angle": 360.0,
		"impact_fraction": 0.45,
		"damage_mult": 2.0,
		"tint": Color(1.0, 0.35, 0.08),
	},
	"Blue": {
		"display_name": "Glacial Sweep",
		"shape": "circle",
		"radius": 7.0,
		"angle": 360.0,
		"impact_fraction": 0.48,
		"damage_mult": 1.9,
		"tint": Color(0.35, 0.75, 1.0),
	},
	"Green": {
		"display_name": "Rooted Slam",
		"shape": "circle",
		"radius": 5.5,
		# Lands late: the clip is a leap, so the impact is the landing.
		"impact_fraction": 0.62,
		"angle": 360.0,
		"damage_mult": 2.6,
		"tint": Color(0.35, 0.9, 0.3),
	},
	"White": {
		"display_name": "Radiant Slash",
		"shape": "cone",
		"radius": 7.5,
		"angle": 130.0,
		"impact_fraction": 0.40,
		"damage_mult": 2.2,
		"tint": Color(1.0, 0.92, 0.55),
	},
	"Black": {
		"display_name": "Charging Headbutt",
		"shape": "cone",
		"radius": 6.0,
		"angle": 70.0,
		"impact_fraction": 0.50,
		"damage_mult": 1.7,
		"tint": Color(0.72, 0.35, 0.95),
	},
}


static func get_visual_scene(color_identity: String) -> PackedScene:
	if not VISUAL_SCENES.has(color_identity):
		return null
	var path: String = VISUAL_SCENES[color_identity]
	if not ResourceLoader.exists(path):
		return null
	return load(path) as PackedScene


static func get_model_scale(color_identity: String, fallback: float) -> float:
	return MODEL_SCALES.get(color_identity, fallback)


static func get_special(color_identity: String) -> Dictionary:
	return SPECIALS.get(color_identity, {})
