extends Node
class_name BossDatabase
## Per-colour boss identity: which model it wears, what its telegraphed specials do, and
## how the fight changes as it loses health.
##
## Each of the five MTG colours gets one boss. The visual scenes are generated by
## tools/boss_character_builder.gd and are all normalized to 1.7 units tall, so
## `model_scale` here is the single knob controlling how physically large a boss
## is - and, through GameSettings.get_boss_anim_speed(), how slowly it animates.
##
## A spawned boss can additionally carry a named, MTG-flavoured MODIFIER (Riot,
## Annihilator, Cataclysm, Bloodthirst, Enrage, Lifelink) that reshapes how the
## SPECIALS below are used, without ever touching this Dictionary itself - see
## GameSettings' Boss modifiers block for every number and EnemyBase.apply_boss_modifier /
## _begin_special for how they're applied to a DUPLICATE of a special's config. This
## Dictionary is shared by every boss of a colour across every match; nothing may mutate it
## in place.
##
## Every boss fights in THREE PHASES (GameSettings' Boss phases block holds the health
## thresholds). Each colour is built to feel different, and the phases are where that lives:
##
##   Red    pressure and tempo       - never lets you stand still, fills the ground with fire
##   Blue   control of space         - slow and readable, but slows you and takes ground away
##   Green  unstoppable weight       - longest tells, biggest hits, brings the forest with it
##   White  discipline and duelling  - lines and crosses, a shield you have to walk around
##   Black  attrition and the hunt   - gets stronger the longer it lasts, hunts the weakest
##
## Phase 2 gives every boss an answer to being kited (something that reaches a player who
## stands off), and phase 3 turns an attack the player already knows into a new one.

## Boss visual scenes are looked up by path rather than preload()ed so a missing
## or not-yet-built scene degrades to the melee fallback in EnemyBase instead of
## failing to parse this script and taking the whole project down with it.
const VISUAL_SCENES := {
	"Red": "res://scenes/bosses/fire_giant.tscn",
	"Blue": "res://scenes/bosses/frost_giant.tscn",
	"Green": "res://scenes/bosses/treant.tscn",
	"White": "res://scenes/bosses/white_paladin.tscn",
	"Black": "res://scenes/bosses/zombie_lord.tscn",
}

## Bigger = slower animations (see GameSettings.boss_anim_reference_scale, which
## is set to the smallest of these so no boss ends up animating faster than 1.0x).
const MODEL_SCALES := {
	"Red": 2.4,
	"Blue": 2.6,
	"Green": 2.9,
	"White": 2.1,
	"Black": 2.3,
}

## Telegraphed, dodgeable special attacks - between them the boss's whole offence. Bosses
## have no ordinary swing at all.
##
## The plain `attack` clip used to drive an undodgeable melee hit on a 1.8s timer, which is the
## one thing in the game a player could not answer: stand in front of a boss and you simply
## took it. Now that clip drives a short-range special - short cooldown, still telegraphed - so
## every hit can be walked out of. What a boss does is entirely made of things the player is
## given a tell for.
##
## Index 0 is always the big phase-1 area attack and index 1 the melee one (the only entry
## flagged hits_crystal). Later entries are the phase specials.
##
## Per-special keys - every one optional except where the shape needs it:
##   clip             which animation drives it ("special", "attack" or "hit")
##   phases           which phases it is used in. Default: all three
##   priority         considered before lower ones when several are ready. Default 0; entries
##                    of equal priority keep their order here, so the big one still wins
##                    wherever it and the melee one are both legal
##   min_range        held back below this distance to the target
##   max_range        and never started from further than this. Default: what the shape reaches
##   cooldown         its own. Default GameSettings.boss_special_cooldown
##   cooldown_by_phase  {phase: seconds}, overriding `cooldown` from that phase on
##   hits_crystal     whether it damages the objective. TRUE only for the melee special: the
##                    crystal cannot dodge, so giving anything else a free hit on it would be
##                    undodgeable damage by another name
##   impact_fraction  where in the clip the hit lands, as a fraction of the clip's own length.
##                    Expressed that way rather than in seconds so the windup stretches for
##                    bigger bosses (whose clips play slower) and the tell stays readable
##   windup           a FIXED tell in seconds instead, for attacks aimed somewhere other than
##                    at the boss's own feet, whose tell must not depend on the clip
##   shape            circle | cone | ring | line | cross
##                      circle  `radius` around its centre
##                      cone    an `angle`-degree arc of `radius` along the facing - dodged by
##                              getting behind it
##                      ring    between `inner_radius` and `radius` - the middle is SAFE
##                      line    `length` x `width` along the facing; `lines` fans several out
##                              at those yaw offsets (degrees)
##                      cross   two lines through the centre at right angles
##   target           who it is aimed at:
##                      current          whoever the boss is already fighting (the default)
##                      nearest_player / farthest_player / weakest_player / random_player
##                      each_player      one strike under every player in range at once
##   anchor           self (centred on the boss, the default) | target (centred where the
##                    target stands) | follow (rides on the boss while it moves)
##   extra_random     each_player only: this many more strikes near a random player
##   move             charge (dashes along its own line as it lands) | leap (travels to the
##                    target over the windup) | follow (walks at the target throughout)
##   slow             seconds of slow on every player it hits
##   hazard           ground it leaves at every centre it struck - see BossHazard
##   hazard_from_phase  only leaves it from this phase on
##   followups        further strikes chained after this one lands, each its own small
##                    special: `delay` after the previous hit, its own `windup`, and an
##                    `anchor` of same (the previous strike's centres), self, follow, or
##                    retarget (turn to a fresh `target` first)
##   exhaust          {time, mult}: after the whole thing ends the boss stands open for
##                    `time` seconds and takes `mult` times damage. The punish window.
##   kind             raise_dead | consecrate - the two that are not a hit at all
##   tell             a tell in the world beside the ground telegraph, for attacks the boss's
##                    body cannot announce on its own - see BossTell. Shown even with
##                    the ground telegraphs switched off
const SPECIALS := {
	# --- RED: pressure and tempo --------------------------------------------------------
	"Red": [
		{
			"display_name": "Whirlwind",
			"clip": "special",
			"phases": [1, 2],
			"shape": "circle",
			"radius": 6.5,
			"angle": 360.0,
			"impact_fraction": 0.45,
			"damage_mult": 2.0,
			"min_range": 3.0,
			"tint": Color(1.0, 0.35, 0.08),
		},
		{
			"display_name": "Cleaving Blow",
			"clip": "attack",
			"shape": "cone",
			"radius": 4.2,
			"angle": 120.0,
			"impact_fraction": 0.45,
			"damage_mult": 1.25,
			"min_range": 0.0,
			"cooldown": 2.2,
			# Phase 3: it simply never stops swinging.
			"cooldown_by_phase": {3: 1.6},
			"hits_crystal": true,
			"tint": Color(1.0, 0.5, 0.2),
		},
		# Phase 2's answer to being kited: a circle under EVERY player in range, plus one more
		# beside a random one so standing still next to a friend is not safe either. Each
		# leaves burning ground, so the field fills up the longer the fight runs.
		{
			"display_name": "Meteor Strike",
			"tell": "meteor",
			"clip": "attack",
			"phases": [2, 3],
			"priority": 1,
			"shape": "circle",
			"radius": 3.0,
			"windup": 1.4,
			"damage_mult": 1.4,
			"cooldown": 10.0,
			"target": "each_player",
			"anchor": "target",
			"extra_random": 1,
			"min_range": 0.0,
			"max_range": 25.0,
			"hazard": {"style": "fire", "radius": 2.5, "duration": 4.0, "dps_mult": 0.25},
			"tint": Color(1.0, 0.45, 0.1),
		},
		# Phase 3: the Whirlwind stops standing still. It walks at its target while it spins
		# and lands three times, so backing straight off no longer works - you leave sideways.
		# Survive it and the giant reels.
		{
			"display_name": "Unbound Whirlwind",
			"clip": "special",
			"phases": [3],
			"shape": "circle",
			"radius": 6.0,
			"impact_fraction": 0.45,
			"damage_mult": 1.0,
			"min_range": 0.0,
			"max_range": 12.0,
			"move": "follow",
			"follow_speed_mult": 0.6,
			"anchor": "follow",
			"followups": [
				{"delay": 0.0, "windup": 0.5, "anchor": "follow", "shape": "circle", "radius": 6.0, "damage_mult": 1.0},
				{"delay": 0.0, "windup": 0.5, "anchor": "follow", "shape": "circle", "radius": 6.0, "damage_mult": 1.0},
			],
			"exhaust": {"time": 2.0, "mult": 1.5},
			"tint": Color(1.0, 0.3, 0.05),
		},
	],
	# --- BLUE: control of space ---------------------------------------------------------
	"Blue": [
		{
			"display_name": "Glacial Sweep",
			"clip": "special",
			"shape": "circle",
			"radius": 7.0,
			"angle": 360.0,
			"impact_fraction": 0.48,
			"damage_mult": 1.9,
			"min_range": 3.0,
			"slow": 2.0,
			# From phase 2 the edge it swept stays frozen - so a player who only ever runs OUT
			# of it runs into ice the next time.
			"hazard": {"style": "frost", "radius": 7.5, "inner_radius": 6.0, "duration": 5.0, "slow": 0.6},
			"hazard_from_phase": 2,
			"tint": Color(0.35, 0.75, 1.0),
		},
		{
			"display_name": "Rime Cleave",
			"clip": "attack",
			"shape": "cone",
			"radius": 4.6,
			"angle": 120.0,
			"impact_fraction": 0.45,
			"damage_mult": 1.25,
			"min_range": 0.0,
			"cooldown": 2.2,
			"hits_crystal": true,
			"tint": Color(0.55, 0.85, 1.0),
		},
		# Phase 2's reach: three lances fanned at the nearest player, long enough to cross
		# most of a lane. Stepping BETWEEN them is the dodge.
		{
			"display_name": "Ice Lances",
			"tell": "ice_spikes",
			"clip": "attack",
			"phases": [2, 3],
			"priority": 1,
			"shape": "line",
			"lines": [-25.0, 0.0, 25.0],
			"length": 14.0,
			"width": 1.6,
			"windup": 1.2,
			"damage_mult": 1.5,
			"cooldown": 9.0,
			"target": "nearest_player",
			"min_range": 0.0,
			"max_range": 16.0,
			"tint": Color(0.6, 0.9, 1.0),
		},
		# Phase 3's signature: a ring. Everything from 3 to 12 units out is lethal and the
		# middle is safe - the exact opposite of what phase 1 taught. And the moment it lands,
		# a Rime Cleave turns on whoever came in, so the safe middle has a back door you
		# still have to find.
		{
			"display_name": "Absolute Zero",
			"tell": "ice_spikes",
			"clip": "special",
			"phases": [3],
			"priority": 2,
			"shape": "ring",
			"inner_radius": 3.0,
			"radius": 12.0,
			"windup": 2.0,
			"damage_mult": 2.2,
			"cooldown": 14.0,
			"target": "nearest_player",
			"min_range": 0.0,
			"max_range": 12.0,
			"followups": [
				{
					"delay": 0.0, "windup": 0.7, "clip": "attack", "anchor": "retarget",
					"target": "nearest_player", "shape": "cone", "radius": 4.6, "angle": 120.0,
					"damage_mult": 1.25,
				},
			],
			"exhaust": {"time": 2.5, "mult": 1.6},
			"tint": Color(0.45, 0.8, 1.0),
		},
	],
	# --- GREEN: unstoppable weight ------------------------------------------------------
	"Green": [
		{
			"display_name": "Rooted Slam",
			"clip": "special",
			"phases": [1],
			"shape": "circle",
			"radius": 5.5,
			# Lands late: the clip is a leap, so the impact is the landing.
			"impact_fraction": 0.62,
			"angle": 360.0,
			"damage_mult": 2.6,
			"min_range": 3.0,
			"tint": Color(0.35, 0.9, 0.3),
		},
		{
			"display_name": "Bough Smash",
			"clip": "attack",
			"shape": "cone",
			"radius": 4.4,
			"angle": 140.0,
			"impact_fraction": 0.5,
			"damage_mult": 1.25,
			"min_range": 0.0,
			"cooldown": 2.4,
			"hits_crystal": true,
			"tint": Color(0.5, 0.95, 0.45),
		},
		# Phase 2: the slam becomes a real leap - at the FARTHEST player. Nobody is safe
		# standing off, and whoever it lands on is slowed. It stays stuck in the ground after.
		{
			"display_name": "Uprooting Leap",
			"tell": "leap_shadow",
			"clip": "special",
			"phases": [2],
			"shape": "circle",
			"radius": 5.5,
			"impact_fraction": 0.62,
			"damage_mult": 2.4,
			"target": "farthest_player",
			"anchor": "target",
			"move": "leap",
			"min_range": 3.0,
			"max_range": 20.0,
			"slow": 1.5,
			"exhaust": {"time": 2.0, "mult": 1.5},
			"tint": Color(0.35, 0.9, 0.3),
		},
		# Phase 3: every landing sends two rings rolling outwards behind it. Jump-rope timing -
		# step into the gap between them rather than running from both.
		{
			"display_name": "Uprooting Leap",
			"tell": "leap_shadow",
			"clip": "special",
			"phases": [3],
			"shape": "circle",
			"radius": 5.5,
			"impact_fraction": 0.62,
			"damage_mult": 2.4,
			"target": "farthest_player",
			"anchor": "target",
			"move": "leap",
			"min_range": 3.0,
			"max_range": 20.0,
			"slow": 1.5,
			"followups": [
				{"delay": 0.0, "windup": 0.8, "anchor": "same", "shape": "ring", "inner_radius": 5.0, "radius": 8.0, "damage_mult": 1.2, "tell": "root_spikes"},
				{"delay": 0.0, "windup": 0.8, "anchor": "same", "shape": "ring", "inner_radius": 8.0, "radius": 11.0, "damage_mult": 1.0, "tell": "root_spikes"},
			],
			"exhaust": {"time": 2.0, "mult": 1.5},
			"tint": Color(0.4, 0.85, 0.25),
		},
	],
	# --- WHITE: discipline and duelling -------------------------------------------------
	"White": [
		{
			"display_name": "Radiant Slash",
			"clip": "special",
			"phases": [1, 2],
			"shape": "cone",
			"radius": 7.5,
			"angle": 130.0,
			"impact_fraction": 0.40,
			"damage_mult": 2.2,
			"min_range": 3.0,
			"tint": Color(1.0, 0.92, 0.55),
		},
		{
			"display_name": "Consecrated Thrust",
			"clip": "attack",
			"shape": "cone",
			# The narrowest of the five melee specials, because a thrust is a line - and it is
			# the one a player can most reliably sidestep rather than back out of.
			"radius": 4.5,
			"angle": 80.0,
			"impact_fraction": 0.45,
			"damage_mult": 1.35,
			"min_range": 0.0,
			"cooldown": 2.0,
			"hits_crystal": true,
			"tint": Color(1.0, 0.95, 0.7),
		},
		# Phase 2's reach: a cross of light centred on a player anywhere in range. Both arms
		# are long - the dodge is the diagonal, not distance.
		{
			"display_name": "Judgment",
			"tell": "light_walls",
			"clip": "special",
			"phases": [2, 3],
			"priority": 1,
			"shape": "cross",
			"length": 16.0,
			"width": 2.0,
			"windup": 1.5,
			"damage_mult": 1.6,
			"cooldown": 9.0,
			"target": "random_player",
			"anchor": "target",
			"min_range": 0.0,
			"max_range": 20.0,
			"tint": Color(1.0, 0.95, 0.6),
		},
		# Phase 3: the slash goes forwards and then straight BACK - aimed at exactly the
		# players phase 2's shield wall sent round behind him.
		{
			"display_name": "Twin Slash",
			"clip": "special",
			"phases": [3],
			"shape": "cone",
			"radius": 7.5,
			"angle": 130.0,
			"impact_fraction": 0.40,
			"damage_mult": 2.2,
			"min_range": 3.0,
			"followups": [
				{"delay": 0.0, "windup": 0.7, "clip": "attack", "anchor": "self", "yaw_offset": 180.0,
				 "shape": "cone", "radius": 7.5, "angle": 130.0, "damage_mult": 1.8},
			],
			"tint": Color(1.0, 0.9, 0.5),
		},
		# Phase 3: kneels and heals. Break it by hitting him hard enough, together, while the
		# golden ring fills - and he is left open. Let it finish and he is back on his feet.
		{
			"display_name": "Consecration",
			"clip": "hit",
			"phases": [3],
			"priority": 2,
			"kind": "consecrate",
			"shape": "circle",
			"radius": 3.0,
			"windup": 4.0,
			"heal_pct": 0.15,
			"break_pct": 0.08,
			"cooldown": 18.0,
			"min_range": 0.0,
			"max_range": 999.0,
			"exhaust": {"time": 3.0, "mult": 1.5},
			"tint": Color(1.0, 0.85, 0.3),
		},
	],
	# --- BLACK: attrition and the hunt --------------------------------------------------
	"Black": [
		# A real charge now: the zombie lord runs the whole line it telegraphed and stops at
		# its far end, rather than headbutting the air in front of it.
		{
			"display_name": "Charging Headbutt",
			"tell": "dust",
			"clip": "special",
			"phases": [1, 2],
			"shape": "line",
			"length": 10.0,
			"width": 2.5,
			"impact_fraction": 0.50,
			"damage_mult": 1.7,
			"min_range": 3.0,
			"max_range": 9.0,
			"move": "charge",
			"dash_time": 0.35,
			"tint": Color(0.72, 0.35, 0.95),
		},
		{
			"display_name": "Grave Maul",
			"clip": "attack",
			"shape": "cone",
			"radius": 4.2,
			"angle": 130.0,
			"impact_fraction": 0.5,
			"damage_mult": 1.25,
			"min_range": 0.0,
			"cooldown": 2.3,
			"hits_crystal": true,
			"tint": Color(0.8, 0.5, 1.0),
		},
		# Phase 2: the dead on the field get back up. Every kill near him is a body he can use
		# - which is what gives Kill and Exalted Strike, the two that leave no corpse, a job
		# in this fight.
		{
			"display_name": "Raise Dead",
			"clip": "attack",
			"phases": [2, 3],
			"priority": 1,
			"kind": "raise_dead",
			"shape": "circle",
			"radius": 1.3,
			"windup": 2.0,
			"raise_count": 4,
			"raise_radius": 12.0,
			"cooldown": 14.0,
			"min_range": 0.0,
			"max_range": 999.0,
			"tint": Color(0.65, 0.25, 0.9),
		},
		# Phase 3: the hunt. Charges at whoever is lowest on health, then turns and charges
		# them again.
		{
			"display_name": "The Hunt",
			"tell": "dust",
			"clip": "special",
			"phases": [3],
			"shape": "line",
			"length": 10.0,
			"width": 2.5,
			"impact_fraction": 0.50,
			"damage_mult": 1.7,
			"target": "weakest_player",
			"min_range": 3.0,
			"max_range": 14.0,
			"move": "charge",
			"dash_time": 0.35,
			"followups": [
				{"delay": 0.1, "windup": 0.8, "clip": "special", "anchor": "retarget", "target": "weakest_player",
				 "shape": "line", "length": 10.0, "width": 2.5, "damage_mult": 1.7, "move": "charge", "dash_time": 0.35,
				 "tell": "dust"},
			],
			"exhaust": {"time": 2.0, "mult": 1.5},
			"tint": Color(0.6, 0.2, 0.9),
		},
	],
}

## What changes about the fight itself at each phase, beyond which specials are in play.
##   name             how the phase banner names this boss
##   titles           {phase: banner text}
##   shockwave        the telegraphed burst a boss lets out as it changes phase
##   lifelink         {from_phase, pct}: heals this share of every hit it lands on a player
##   shield_wall_from_phase  frontal damage reduction from this phase on (see GameSettings)
##   saplings_on_phase       grows saplings when this phase begins
##   fog_surge        {mult, seconds}: thickens this colour's lane fog at each phase change
const PHASES := {
	"Red": {
		"name": "FIRE GIANT",
		"titles": {2: "KINDLED", 3: "UNBOUND"},
		"shockwave": {"display_name": "Ember Shock", "tint": Color(1.0, 0.4, 0.1)},
	},
	"Blue": {
		"name": "FROST GIANT",
		"titles": {2: "WINTER'S GRIP", 3: "ABSOLUTE ZERO"},
		"shockwave": {"display_name": "Frost Nova", "tint": Color(0.5, 0.85, 1.0)},
	},
	"Green": {
		"name": "TREANT",
		"titles": {2: "THE FOREST WAKES", 3: "EARTHQUAKE"},
		"shockwave": {"display_name": "Roar of the Wild", "tint": Color(0.45, 0.95, 0.35)},
		"saplings_on_phase": 2,
	},
	"White": {
		"name": "PALADIN",
		"titles": {2: "SHIELD WALL", 3: "CONSECRATED"},
		"shockwave": {"display_name": "Radiant Burst", "tint": Color(1.0, 0.93, 0.6)},
		"shield_wall_from_phase": 2,
	},
	"Black": {
		"name": "ZOMBIE LORD",
		"titles": {2: "THE DEAD RISE", 3: "THE HUNT"},
		"shockwave": {"display_name": "Grave Howl", "tint": Color(0.7, 0.3, 0.95)},
		"lifelink": {"from_phase": 2, "pct": 0.2},
		# The swamp closes in around him for a few seconds at each phase change. Telegraphs
		# are emissive and stay readable through it; the lane beyond them does not.
		"fog_surge": {"mult": 1.8, "seconds": 6.0},
	},
}


static func get_visual_scene(color_identity: String) -> PackedScene:
	if not VISUAL_SCENES.has(color_identity):
		return null
	var path: String = VISUAL_SCENES[color_identity]
	if not ResourceLoader.exists(path):
		return null
	return load(path) as PackedScene


static func get_model_scale(color_identity: String, fallback: float) -> float:
	return MODEL_SCALES.get(color_identity, fallback)


## Every special this colour's boss has, across all three phases. EnemyBase filters them by
## phase and orders them by priority; see the SPECIALS comment.
static func get_specials(color_identity: String) -> Array:
	return SPECIALS.get(color_identity, [])


static func get_phase_config(color_identity: String) -> Dictionary:
	return PHASES.get(color_identity, {})


## Whether `config` is in play during `phase`.
static func special_in_phase(config: Dictionary, phase: int) -> bool:
	return (config.get("phases", [1, 2, 3]) as Array).has(phase)
